name: Inspect
on: [push]
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Fetch Deps
      shell: bash
      run: yarn
  lint:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Lint
      shell: bash
      run: yarn lint
  build:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - uses: actions/checkout@v2
    - name: Cache Deps
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build
      shell: bash
      run: yarn build
    - name: Upload Builds
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
